import React, { Component } from 'react';
import { View, Text, ScrollView, TouchableOpacity } from 'react-native'
import { Card, CardItem, Body, Icon, Left, Right, CheckBox, } from 'native-base';
import { orange } from '../color'


class datapolicy extends Component {

  render() {
    return (
      <View style={{ flex: 1 }}>
        <View style={{ flexDirection: 'row', backgroundColor: orange, width: '100%', height: '10%', shadowColor: "#000", shadowOffset: { width: 0, height: 1, }, shadowOpacity: 0.22, shadowRadius: 2.22, elevation: 5, }}>
          <TouchableOpacity>
            <Icon style={{ paddingLeft: '5%', color: 'white', paddingTop: '3%' }} name='arrowleft' type='AntDesign' />
          </TouchableOpacity>
          <Text style={{ alignSelf: 'center', paddingLeft: '7%', fontSize: 20, color: 'white' }}>Data Policy</Text>
        </View>
        <ScrollView style={{ flex: 1, flexDirection: 'column' }}>
          <View style={{ marginTop: '5%', paddingLeft: '4%' }}>
            <Text style={{ fontSize: 18, color: 'black' }}>This policy explains how we, delish, a brand of http://www.delish.com, use your personal information which you provide to us when using our service, including but not limited to our website and mobile applications (apps).</Text>
          </View>

          <View style={{ marginTop: '5%', paddingLeft: '4%' }}>
            <Text style={{ fontWeight: 'bold', fontSize: 18, color: 'black' }}>What information we collect about you?</Text>
          </View>
          <View style={{ marginTop: '5%', paddingLeft: '4%' }}>
            <Text style={{ fontSize: 18, color: 'black' }}>We collect personal information from you when you order goods or services from us or use our website. We also collect information when you complete any customer survey. Website usage information may also be collected using cookies.</Text>
          </View>
          <View style={{ marginTop: '5%', paddingLeft: '4%' }}>
            <Text style={{ fontWeight: 'bold', fontSize: 18, color: 'black' }}>Cookies and Google Analytics</Text>
          </View>
          <View style={{ marginTop: '5%', paddingLeft: '4%' }}>
            <Text style={{ fontSize: 18, color: 'black' }}>Cookies are small text files that are placed on your computer by websites that you visit. They are widely used in order to make websites work, or work more efficiently, as well as to provide information to the owners of the site.</Text>
          </View>
          <View style={{ marginTop: '5%', paddingLeft: '4%' }}>
            <Text style={{ fontSize: 18, color: 'black' }}>This website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies", which are text files saved on your computer, to help the website analyze how you use the site. The information generated by the cookie about your use of the website will be transmitted to and stored by Google on servers in the United States. If this website anonymizes IP addresses, your IP address will be truncated by Google within a EU member state or other EEA state before being transmitted to the US. Only in exceptional situations will your full IP address be transmitted to Google servers in the United States and truncated there. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above. You can also prevent Google from collecting information (including your IP address) via cookies and processing this information by downloading this browser plugin and installing it: https://tools.google.com/dlpage/gaoptout</Text>
          </View>
          <View style={{ marginTop: '2%', paddingLeft: '4%', paddingBottom: '10%' }}>
            <Text style={{ fontSize: 18, color: 'black' }}>Most web browsers allow some control of most cookies through the browser settings. To find out more about cookies, including how to see what cookies have been set and how to manage and delete them, visit www.allaboutcookies.org.</Text>
          </View>
        </ScrollView>

      </View>
    );
  }
}


export default datapolicy;